### ISSUE TITLE
Firebase 3

### ISSUE THREAD

**Issue by mkiisoft** [doowb/firebase-cron#4]
Does this work with Firebase 3 and Firebase Hosting? Do I have to build my own server?

I need to take all the ratings from one key, calculate the rate and update the value... but I can't find any info about it.

Thanks in advance!

**Comment by doowb** [comment]
It should work with Firebase 3 since the references are passed into this library after you create them. There might be an API change in Firebase 3 that I might have to account for. If you try it and find errors, please open an issue so I can get it fixed.

The idea of this library is that you use it with [firebase-queue](https://github.com/firebase/firebase-queue) to add tasks to a queue at scheduled times.

In your case, I would create a cron job that puts the ratings key into a queue task at your specified time interval. Then your queue task will do the calculating and updating based on the ratings key.

If you just need to do that in near real-time (when a rating for a key is updated), then you probably don't need firebase-cron and can just add the key to your queue task to do the processing.

> Firebase Hosting

As far as I know, firebase hosting is only for static files. You'll need another service like heroku or google app engine to run a server running your firebase-queue and firebase-cron instances.

For more answers on your idea,  you can try stack overflow or the firebase google group.

I'm going to close this, but please feel free to create new issues if you run into problems using firebase 3.
