### ISSUE TITLE
Using multiple queueRef in the same cron?

### ISSUE THREAD

**Issue by jeremyputeaux** [doowb/firebase-cron#6]
I would like to use firebase-cron to push multiple types of tasks but it seems like one cron is limited to one task.
Can I use the same cron to push task with differents names?

Thanks for making firebase-cron. It's great!

**Comment by doowb** [comment]
Currently, only a single queue is used, but you can use [firebase-queue specs](https://github.com/firebase/firebase-queue/blob/master/docs/guide.md#defining-specs-optional) to make something like this work.

Basically create a job with that has a `start_state` on the `data` object for your specific spec:

```js
cron.addJob('foo', '00 00 00 * * *', {start_state: 'custom-spec-start-state', foo: 'bar'}, function(err) {
  if (err) return console.error(err);
  console.log('job added');
});
```

I'm also open to refactoring to only passing in the root firebase ref and having more metadata around a job. The metadata could specify the queue the job data should be push to, then that can be spread out among multiple queues and specs if necessary. So instead of doing `this.queue.child('tasks').push(data)`, it would be something like `this.ref.child(job.queue).child('tasks').push(data)`.

I like this idea and if anyone is interested in doing a PR, let me know. This will make using dynamically created queues and scaling easier.

**Comment by jeremyputeaux** [comment]
You are right. It's working thanks!
